[package]
name = "thedes-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
thedes-async-util = { path = "../thedes-async-util" }
thedes-geometry = { path = "../thedes-geometry" }
crossterm = "0.28.1"
