[package]
name = "thedes-graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
num = { workspace = true }
thiserror = { workspace = true }
thedes-domain = { path = "../thedes-domain" }
thedes-tui = { path = "../thedes-tui" }
