name: Thedes CI - GH Pages
on: 
  push:
    branches:
      - master

jobs:
  deploy-pages:
    timeout-minutes: 15
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Update rustup
        run: rustup update stable && rustup default stable

      - name: Document native
        run: cargo doc --all-features --workspace

      - name: Move docs
        run: |
          mv target/doc/ public/
          rm -rf target/

      - name: Add helper pages
        run: ./docs-pages/_build.sh public/

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
